'use strict';

// validation-rules.js
// Declarative data describing every validation rule (id, category,
// severity, message templates, etc). Consumed by validation.js.
// Depends on: nothing.

// ─────────────────────────────────────────────────────────────────
// RULES DATA
// ─────────────────────────────────────────────────────────────────
const RULES_DATA = {
  categories: {
    'question-structure': 'Question Structure',
    'html-tags':          'HTML Tag Integrity',
    'images':             'Image Tag Integrity',
    'span-metadata':      'Span Metadata',
    'groups-points':      'Question Groups & Points',
    'tables':             'Table Structure',
    'accessibility':      'Special Character Check'
  },
  rules: [
    { id:'no-space-in-code', category:'question-structure', severity:'error',
      description:'No spaces allowed around colons in question type codes',
      type:'code-spacing',
      message:'Question code has extra spaces: "{found}". Use mc:radio: not mc : radio :',
      fix:{description:'Remove all spaces around colons in the question type code.',
           snippet:'mc:radio:  essay:  fib:  tf:  matching:label:'} },
    
  { id:'intra-question-blank-lines', category:'question-structure', severity:'error',
      description:'Blank lines are not allowed within a question block',
      type:'intra-question-blank-check',
      message:'Question {num} contains a blank line. Remove all blank lines within the question.',
      fix:{description:'Remove the empty line inside the question.',
           snippet:'mc:radio:...\nCorrect\nx-Wrong\npoints:1\ngroup:1'} },

    { id:'question-spacing', category:'question-structure', severity:'error',
      description:'Questions must be separated by exactly one blank line',
      type:'question-spacing',
      message:'{found} between Q{a} and Q{b} — must be exactly one blank line.',
      fix:{description:'Ensure exactly one blank line appears between each pair of questions. Remove extra blank lines or add a missing one.',
           snippet:'points:2\ngroup:1\n                 <- exactly one blank line between\nmc:radio:<span ...'} },

    { id:'groups-sequential', category:'groups-points', severity:'error',
      description:'Groups must be sequential — all group 1 together, then group 2, etc.',
      type:'group-sequence',
      message:'Group sequence error: group:{found} appears after group:{previous}.',
      fix:{description:'Reorder so all group 1 questions come first, then group 2, etc.',
           snippet:'...group:1\n\n...group:1\n\n...group:2  <- group 2 starts here'} },

    { id:'groups-contiguous', category:'groups-points', severity:'error',
      description:'Group numbers must start at 1 and increase by exactly 1 with no gaps',
      type:'group-numbering',
      message:'Group numbering error: {found}.',
      fix:{description:'Renumber groups so they start at 1 and increment by 1 with no gaps (1, 2, 3…). Every group number in the sequence must be used.',
           snippet:'group:1  <- first group\ngroup:2  <- next\ngroup:3  <- no skipping'} },

    { id:'points-present', category:'groups-points', severity:'error',
      description:'Every question must have a points: line',
      type:'question-has-field', field:'points',
      message:'Question {num} is missing a points: line.',
      fix:{description:'Add points: before group: at the end of the question.',
           snippet:'x-Correct\nWrong\npoints:3\ngroup:1'} },

    { id:'group-present', category:'groups-points', severity:'error',
      description:'Every question must have a group: line',
      type:'question-has-field', field:'group',
      message:'Question {num} is missing a group: line.',
      fix:{description:'Add group: after points: at the end of the question.',
           snippet:'x-Correct\nWrong\npoints:3\ngroup:1'} },

    { id:'points-before-group', category:'groups-points', severity:'error',
      description:'points: must appear before group:',
      type:'field-order',
      message:'Question {num} has group: before points:. Correct order: points: then group:.',
      fix:{description:'Swap so points: always comes before group:.',
           snippet:'points:3\ngroup:1'} },

    { id:'same-group-same-type', category:'groups-points', severity:'error',
      description:'All questions in a group must be the same type',
      type:'group-type-consistency',
      message:'Group {group} mixes question types: {types}.',
      fix:{description:'Ensure every question in a group uses the same type code.',
           snippet:'mc:radio:Question A\npoints:3\ngroup:1\n\nmc:radio:Question B\npoints:3\ngroup:1'} },

    { id:'same-group-same-points', category:'groups-points', severity:'error',
      description:'All questions in a group must have the same point value',
      type:'group-points-consistency',
      message:'Group {group} has inconsistent point values: {values}.',
      fix:{description:'All questions in the same group must share the same points value.',
           snippet:'points:3\ngroup:1\n\npoints:3  <- must match\ngroup:1'} },

    { id:'same-group-same-meta', category:'groups-points', severity:'error',
      description:'All questions in a group must have identical span metadata',
      type:'group-meta-consistency',
      message:'Group {group} has inconsistent span metadata across questions.',
      fix:{description:'Every question in the same group must have exactly the same <span> tag, including data-complexity, data-associatedlessons, data-standard-*, and the visible (xx.xx LC|MC|HC) text inside the span.',
           snippet:'mc:radio:<span data-standard-florida="MA.5.NSO.1.1" data-complexity="LC" data-associatedlessons="01.01R">(01.01 LC)</span><br /><br />Question text...'} },

    { id:'mc-radio-one-correct', category:'question-structure', severity:'error',
      description:'mc:radio questions must have exactly one correct answer (x-)',
      type:'mc-correct-count',
      message:'Question {num} has {count} correct answers marked. Must be exactly 1.',
      fix:{description:'Mark exactly one answer with x- prefix.',
           snippet:'x-Correct answer\nWrong answer\nWrong answer'} },

    { id:'tf-answer-valid', category:'question-structure', severity:'error',
      description:'tf: questions must list only one of true or false, not both',
      type:'tf-answer',
      message:'Question {num} lists both true and false as answers.',
      fix:{description:'A tf: question should list only the correct answer.',
           snippet:'tf:The sky is blue.\ntrue'} },

    { id:'tf-answer-present', category:'question-structure', severity:'error',
      description:'tf: questions must have exactly one answer — either true or false',
      type:'tf-answer-present',
      message:'Question {num} has no valid answer. Must be exactly one of: true, false.',
      fix:{description:'Add either true or false as the answer line.',
           snippet:'tf:The sky is blue.\ntrue'} },

    { id:'malformed-html-tag', category:'html-tags', severity:'error',
      description:'HTML tags must have matching opening and closing angle brackets',
      type:'malformed-tags',
      message:'Line {line} has a malformed HTML tag: "{found}".',
      fix:{description:'Ensure every < has a matching >.',
           snippet:'<br />  not  <br\n<img src="..." />  not  <img src="..."'} },

    { id:'self-closing-br', category:'html-tags', severity:'error',
      description:'Line breaks must be written as <br />',
      type:'br-format',
      message:'Line {line} has "{found}" — must be <br />.',
      fix:{description:'Replace all br variants with exactly <br />.',
           snippet:'<br />  (correct)\n<br>  <BR>  </br>  (wrong)'} },

    { id:'no-inline-styles', category:'html-tags', severity:'error',
      description:'Inline style attributes are not allowed except on img (vertical-align:middle), ol (list-style-type), table elements (text-align), and any element with style="text-align: ..." or dir="..."',
      type:'inline-style-check',
      message:'Line {line} has a disallowed inline style attribute.',
      fix:{description:'Remove the style attribute. Allowed exceptions: style="vertical-align:middle;" on img tags, style="list-style-type:..." on ol tags, style="text-align: [any]" on any element, and dir="[any]" on any element.',
           snippet:'<img src="..." alt="..." style="vertical-align:middle;" />\n<ol style="list-style-type: upper-roman;">\n<p style="text-align: center;">text</p>\n<p dir="rtl">text</p>'} },

    { id:'no-deprecated-tags', category:'html-tags', severity:'error',
      description:'Deprecated tags <b>, <i>, <u>, <s> must be replaced with semantic equivalents',
      type:'forbidden-html-tags',
      tags:['<b>','</b>','<i>','</i>','<u>','</u>','<s>','</s>','<bold>','</bold>','<italic>','</italic>'],
      message:'Line {line} uses deprecated tag "{found}".',
      fix:{description:'Replace deprecated tags: <b>→<strong>, <i>→<em>, <u>→<span class="underline">, <s>→<del>. Remove <bold> and <italic> entirely.',
           snippet:'<strong>bold</strong>  <em>italic</em>  <del>struck</del>'} },

    { id:'mark-tag', category:'html-tags', severity:'error',
      description:'<mark> tags and remnants must be removed — not supported in assessments',
      type:'mark-tag-check',
      message:'Line {line} contains {found}.',
      fix:{description:'Remove all <mark> opening tags, </mark> closing tags, and any partial remnants. Complete tags can be auto-removed with Apply Fix — partial remnants must be reviewed and removed manually.',
           snippet:'<!-- Remove entirely -->\n<mark class="highlight">text</mark>  →  text\n\n<!-- Partial remnants also need removing -->\nmark class="highlight">  →  (delete)\n/mark>  →  (delete)'} },

    { id:'no-commented-code', category:'html-tags', severity:'error',
      description:'HTML comments containing code must be removed',
      type:'commented-html',
      message:'Line {line} contains HTML tags inside a comment.',
      fix:{description:'Remove the commented-out HTML block entirely.',
           snippet:'<!-- comments with <tags> inside are not allowed -->'} },

    { id:'unclosed-paired-tags', category:'html-tags', severity:'error',
      description:'Paired HTML tags must have matching open and close tags',
      type:'unclosed-paired-tags-check',
      message:'Question {num} has {found} — every opening tag needs a matching closing tag.',
      fix:{description:'Add the missing closing tag, or remove the orphaned opening tag.',
           snippet:'<strong>text</strong>  <em>text</em>  <sup>2</sup>  <sub>2</sub>'} },

    { id:'lt-gt-entities', category:'html-tags', severity:'error',
      description:'Math/code symbols (<, >) and entities (&lt;, &gt;, &le;, &ge;) must be wrapped in <span>',
      type:'lt-gt-entities-check',
      message:'Line {line} contains unspanned "{found}" — wrap in <span> to prevent LMS parsing errors.',
      fix:{description:'Wrap naked < and > symbols (or their html entities) in <span> tags so the LMS does not misinterpret them as broken HTML.',
           snippet:'\nx < y\np &gt; 5\n\n\nx <span><</span> y\np <span>></span> 5'} },

    { id:'img-has-alt', category:'images', severity:'error',
      description:'Every image must have a non-empty alt attribute',
      type:'img-alt-check',
      message:'Line {line} has an <img> missing a non-empty alt attribute.',
      fix:{description:'Add a descriptive alt attribute to the img tag.',
           snippet:'<img src="image.jpg" alt="Description of the image." />'} },

    { id:'img-double-quotes', category:'images', severity:'error',
      description:'Image src and alt attributes must use double quotes',
      type:'img-quote-check',
      message:'Line {line} uses single quotes on an img attribute.',
      fix:{description:'Change single quotes to double quotes on src and alt.',
           snippet:'<img src="image.jpg" alt="Description." />'} },

    { id:'img-format', category:'images', severity:'warning',
      description:'Images should use .jpg, .gif, .png, or .svg format',
      type:'img-extension-check', allowed:['.jpg','.jpeg','.gif','.png','.svg'],
      message:'Line {line} image has unsupported extension "{found}".',
      rationale:'Unsupported formats may not render correctly in the assessment player. Stick to jpg, gif, png, or svg.',
      fix:{description:'Convert the image to jpg, gif, png, or svg.',
           snippet:'image.jpg  image.png  image.gif  image.svg'} },

    { id:'img-alt-quotes', category:'images', severity:'error',
      description:'Double quotes inside alt text must be replaced with single quotes',
      type:'img-alt-quotes-check',
      message:'Line {line} alt text contains double quotes — use single quotes inside alt.',
      fix:{description:'Replace " with \' inside the alt text.',
           snippet:"alt=\"A 'quoted' word\"  not  alt=\"A \\\"quoted\\\" word\""} },

    { id:'img-alt-html', category:'images', severity:'error',
      description:'Alt text must not contain HTML tags',
      type:'img-alt-html-check',
      message:'Line {line} alt text contains HTML: "{found}".',
      fix:{description:'Remove all HTML tags from the alt text.',
           snippet:'alt="Plain text description only."'} },

    { id:'img-alt-symbol-words', category:'images', severity:'warning',
      description:'Symbols in alt text must be spelled out',
      type:'img-alt-symbol-check',
      message:'Line {line} alt text contains symbol "{found}" — spell it out.',
      rationale:'Screen readers speak alt text aloud. Symbols like >, <, %, + are not pronounced correctly — they must be written as words (e.g. "greater than", "percent", "plus").',
      fix:{description:'Replace symbols with words: > = greater than, < = less than, % = percent, etc.',
           snippet:'alt="a graph showing values greater than 50 percent"'} },

    { id:'img-alt-unknown-symbol', category:'images', severity:'warning',
      description:'Unusual symbols in alt text should be reviewed',
      type:'img-alt-unknown-symbol-check',
      message:'Line {line} alt text contains unusual symbol "{found}" — review.',
      rationale:'Alt text is read aloud by screen readers. Unusual characters may be skipped, mispronounced, or cause confusion. Spell out or remove any non-standard symbols.',
      fix:{description:'Ensure all symbols in alt text are spelled out or removed.',
           snippet:'Alt text should read naturally when spoken aloud.'} },

    { id:'img-no-dimensions', category:'images', severity:'error',
      description:'Images must not have height or width attributes',
      type:'img-dimensions-check',
      message:'Line {line} <img> has a "{found}" attribute — remove it.',
      fix:{description:'Remove width and height attributes from img tags.',
           snippet:'<img src="image.jpg" alt="desc" />  (no width or height)'} },

    { id:'img-extra-attributes', category:'images', severity:'warning',
      description:'Images should only have src, alt, and optionally style="vertical-align:middle;"',
      type:'img-extra-attrs-check',
      message:'Line {line} <img> has unexpected attribute(s): {found}.',
      rationale:'Extra attributes on img tags (like title, class, id, or data-*) are not supported by the assessment player and will be stripped or may cause rendering issues.',
      fix:{description:'Remove attributes other than src, alt, and the allowed style.',
           snippet:'<img src="..." alt="..." />'} },

    { id:'img-path-format', category:'images', severity:'error',
      description:'Image paths must be lowercase and without spaces',
      type:'img-path-check',
      message:'Line {line} image path "{found}" has spaces or capitals.',
      fix:{description:'Ensure file name and path are in lowercase and without spaces.',
           snippet:''} },

    { id:'img-path-base', category:'images', severity:'error',
      description:'Image src must use the required CDN base path',
      type:'img-path-base-check',
      message:'Line {line} image src "{found}" — expected path starting with {expected}.',
      fix:{description:'Update the src to use the correct CDN base path and course folder. Use Apply Fix to replace the folder segment automatically when a course folder is set.',
           snippet:'<img src="//cdn.flvs.net/assessment_images/my_course_v1/image.jpg" alt="..." />'} },
    
  { id:'span-attr-quotes', category:'span-metadata', severity:'error',
      description:'Metadata attributes must use matching double quotes',
      type:'span-attr-quotes-check',
      message:'Question {num} metadata attribute "{found}" has missing or mismatched quotes.',
      fix:{description:'Ensure all metadata attribute values are wrapped in matching double quotes.',
           snippet:'data-complexity="LC"\ndata-associatedlessons="01.01R"'} },
    
    { id:'missing-lt-span', category:'span-metadata', severity:'error',
      description:'Question code must be followed by <span — missing opening angle bracket',
      type:'missing-lt-span-check',
      message:'Line {line} has "{found}" — the < is missing before span.',
      fix:{description:'Insert the missing < before span after the question type code.',
           snippet:'<!-- Wrong -->\nmc:radio:span ...>(...)</span>\n\n<!-- Correct -->\nmc:radio:<span ...>(...)</span>'} },

    { id:'span-missing', category:'span-metadata', severity:'error',
      description:'Every question must open with a metadata <span> immediately after the question code',
      type:'span-missing-check',
      message:'Question {num} has no metadata <span> tag. All questions must begin with a <span> containing data-standard-*, data-complexity, and data-associatedlessons.',
      fix:{description:'Add a metadata span immediately after the question type code.',
           snippet:'mc:radio:<span data-standard-florida="VA.68.C.3.1" data-complexity="LC" data-associatedlessons="02.01R">(02.01 LC)</span><br /><br />Question stem here.'} },

    { id:'span-unclosed', category:'span-metadata', severity:'error',
      description:'Metadata <span> must have a matching </span> closing tag',
      type:'span-unclosed-check',
      message:'Question {num} has an opening <span> with no matching </span>.',
      fix:{description:'Add the missing </span> closing tag after the span content.',
           snippet:'<span data-standard-florida="..." data-complexity="LC" data-associatedlessons="02.01R">(02.01 LC)</span>'} },

    { id:'span-data-standard', category:'span-metadata', severity:'error',
      description:'Metadata span must include at least one data-standard-[state] attribute',
      type:'span-data-standard-check',
      message:'Question {num} span is missing a data-standard-* attribute or its value is blank.',
      fix:{description:'Add a data-standard-[identifier] attribute with a non-empty value.',
           snippet:'<span data-standard-florida="26.01" data-complexity="LC" data-associatedlessons="03.01R">(03.01 LC)</span>'} },

    { id:'span-data-complexity', category:'span-metadata', severity:'error',
      description:'Metadata span must have data-complexity set to LC, MC, or HC',
      type:'span-attribute-check', attribute:'data-complexity', validValues:['LC','MC','HC'],
      message:'Question {num} span has invalid data-complexity "{found}". Valid: LC, MC, HC.',
      fix:{description:'Set data-complexity to LC, MC, or HC.',
           snippet:'<span data-complexity="LC" ...>(03.01 LC)</span>'} },

    { id:'span-data-associatedlessons', category:'span-metadata', severity:'error',
      description:'Metadata span must include data-associatedlessons attribute',
      type:'span-attribute-check', attribute:'data-associatedlessons',
      message:'Question {num} span is missing the data-associatedlessons attribute.',
      fix:{description:'Add data-associatedlessons matching the lesson reference.',
           snippet:'<span data-associatedlessons="02.01R" ...>(02.01 LC)</span>'} },

    { id:'span-associatedlessons-format', category:'span-metadata', severity:'error',
      description:'Each lesson in data-associatedlessons must follow ##.##R or ##.##H format with two-digit numbers',
      type:'span-associatedlessons-format-check',
      message:'Question {num} data-associatedlessons "{found}" — each entry must match ##.##R or ##.##H format.',
      fix:{description:'Each lesson must be exactly ##.##R or ##.##H — two digits on each side of the dot, ending with R or H. Separate multiples with |.',
           snippet:'data-associatedlessons="03.01R"\ndata-associatedlessons="03.01R|03.02H"\n\n1.03R  →  01.03R  (zero-pad single digits)'} },

    { id:'span-followed-by-br', category:'span-metadata', severity:'error',
      description:'Metadata span must be immediately followed by <br /><br />',
      type:'span-br-check',
      message:'Question {num} span is not followed by <br /><br />.',
      fix:{description:'Add exactly <br /><br /> immediately after </span>.',
           snippet:'<span ...>(03.01 LC)</span> <br /><br />'} },

    { id:'span-content-match', category:'span-metadata', severity:'error',
      description:'Span content must match data-complexity and data-associatedlessons',
      type:'span-content-match-check',
      message:'Question {num} span content "{found}" does not match its attributes.',
      fix:{description:'The text inside the span must be (lesson complexity) matching the attributes.',
           snippet:'<!-- data-complexity="LC" data-associatedlessons="03.01R" -->\n<span ...>(03.01 LC)</span>'} },

    { id:'span-self-closing', category:'span-metadata', severity:'error',
      description:'Metadata <span> must not be self-closing — remove the stray / before the closing >',
      type:'span-self-closing-check',
      message:'Question {num} metadata span tag ends with /> instead of > — the / must be removed.',
      fix:{description:'Remove the / from the opening span tag. A <span> is not a void element and must never be self-closed.',
           snippet:'<!-- Wrong -->\n<span data-standard-florida="..." data-complexity="LC" data-associatedlessons="02.01R" />\n\n<!-- Correct -->\n<span data-standard-florida="..." data-complexity="LC" data-associatedlessons="02.01R">'} },

    { id:'matching-dash-separator', category:'question-structure', severity:'error',
      description:'Each matching answer must use a dash ( - ) to separate term from definition',
      type:'matching-format',
      message:'Question {num} matching answer on line {line} is missing the dash separator.',
      fix:{description:'Format each pair as: term-definition',
           snippet:'hatching-parallel lines drawn close together\ncrosshatching-lines in two directions'} },

    { id:'matching-points-multiple', category:'question-structure', severity:'warning',
      description:'Matching question points should be a multiple of the number of pairs',
      type:'matching-points-check',
      message:'Question {num} has {pairs} pairs but points:{points} is not a multiple of {pairs}.',
      rationale:'Matching questions are scored one point per correct pair. If total points is not a multiple of the pair count, fraction of points occurs.',
      fix:{description:'Set points to a multiple of the pair count.',
           snippet:'3 pairs -> points:3 or points:6\n4 pairs -> points:4 or points:8'} },

    { id:'matching-min-pairs', category:'question-structure', severity:'error',
      description:'Matching questions must have at least 3 answer pairs',
      type:'matching-min-pairs-check',
      message:'Question {num} has only {count} matching pair(s) — a minimum of 3 is required.',
      fix:{description:'Add more term-definition pairs so there are at least 3 matches.',
           snippet:'term1-definition one\nterm2-definition two\nterm3-definition three'} },

    { id:'matching-right-side-length', category:'question-structure', severity:'error',
      manualFixOnly: true,
      description:'Matching: text after the dash must be 42 characters or fewer',
      type:'matching-right-side-length-check',
      message:'Question {num} has {count} matching answer(s) with right-side text longer than 42 characters. Rewrite to shorten, or swap the left and right sides.',
      fix:{description:'Matching answer text (right-side) longer than 42 characters.',
           htmlDescription:'Matching answer text (right-side) longer than 42 characters.<br><br><table style="width:100%; border-collapse:collapse; font-size:11.5px; margin-bottom:8px;"><tr><th style="border:1px solid var(--border); padding:6px 8px; background:var(--surface2); text-align:left;">Options</th><th style="border:1px solid var(--border); padding:6px 8px; background:var(--surface2); text-align:left;">Fix</th></tr><tr><td style="border:1px solid var(--border); padding:6px 8px; vertical-align:middle;"><strong>Option 1: Rewrite</strong></td><td style="border:1px solid var(--border); padding:6px 8px; vertical-align:middle;">Rewrite the right-side text to fit within the 42 character max length</td></tr><tr><td style="border:1px solid var(--border); padding:6px 8px; vertical-align:middle; white-space:nowrap;"><strong>Option 2:</strong>{{SWAP_BTN}}</td><td style="border:1px solid var(--border); padding:6px 8px; vertical-align:middle;">Rearrange by placing the longer text on the left-side</td></tr></table>'} },

   { id:'matching-html-on-right', category:'question-structure', severity:'error',
      description:'Matching: HTML tags and images must appear on the left side of the dash, not the right',
      type:'matching-html-on-right-check',
      message:'Question {num} has {count} matching answer(s) with HTML or image tags on the right side. Swap the left and right sides so the HTML is on the left.',
      fix:{description:'The LMS cannot render HTML or images on the right side of a matching pair. Swap the left and right sides so the HTML/image is on the left.',
           snippet:''} },

    { id:'matching-img-align', category:'images', severity:'error',
      description:'Images in matching answers must not use the align attribute — use style="vertical-align:middle;" or no alignment at all',
      type:'matching-img-align-check',
      message:'Question {num} line {line}: matching image uses align="{found}" — remove this attribute. Use style="vertical-align:middle;" if needed, or no alignment attribute at all.',
      fix:{description:'The align attribute is not valid on images in matching answers. Remove it entirely. You may optionally add style="vertical-align:middle;" if needed for rendering, but no alignment attribute is also correct.',
           snippet:'<!-- Wrong -->\n<img src="..." alt="..." align="middle" />\n<img src="..." alt="..." align="absmiddle" />\n\n<!-- Correct (with optional style) -->\n<img src="..." alt="..." style="vertical-align:middle;" />\n\n<!-- Also correct (no alignment) -->\n<img src="..." alt="..." />'} },

    { id:'span-lang-valid', category:'html-tags', severity:'error',
      description:'<span lang="..."> tags must be well-formed with a valid, non-empty language code',
      type:'span-lang-check',
      message:'Line {line} has a <span lang> issue: {found}.',
      fix:{description:'Ensure the lang attribute is present, non-empty, and uses a valid BCP-47 language tag.',
           snippet:'<span lang="es">texto en español</span>\n<span lang="fr">texte en français</span>\n<span lang="zh-Hans">简体中文</span>'} },

    { id:'ol-use-style-not-type', category:'html-tags', severity:'error',
      description:'Ordered lists must use style="list-style-type:..." instead of the type attribute',
      type:'ol-type-check',
      message:'Line {line} uses <ol type="{found}"> — replace with equivalent inline style.',
      fix:{description:'Replace the type attribute with the equivalent style="list-style-type:..." inline style.',
           snippet:'<!-- Wrong -->\n<ol type="A">  <ol type="i">  <ol type="1">\n\n<!-- Correct -->\n<ol style="list-style-type: upper-alpha;">\n<ol style="list-style-type: lower-roman;">\n<ol style="list-style-type: decimal;">'} },

   { id:'bare-url-in-text', category:'html-tags', severity:'error',
      description:'URLs in question text must be wrapped in <span></span> to prevent auto-linking',
      type:'bare-url-check',
      message:'Line {line} contains a bare URL "{found}" — wrap it in <span> to prevent auto-hyperlinking.',
      rationale:'Some LMS platforms automatically convert plain URLs into clickable hyperlinks, which breaks assessment formatting. Wrapping in <span></span> prevents this.',
      fix:{description:'Wrap the URL in a <span> tag.',
           snippet:'<!-- Wrong -->\nhttps://www.example.com\n\n<!-- Correct -->\n<span>https://www.example.com</span>'} },

    { id:'img-inline-needs-valign', category:'images', severity:'error',
      description:'Images inline with text must have style="vertical-align:middle;"',
      type:'img-inline-valign-check', subtype:'missing',
      message:'Line {line} has an inline image (no <br /> on either side) without style="vertical-align:middle;".',
      fix:{description:'Add style="vertical-align:middle;" to any image that appears inline alongside text. Images on their own line (surrounded by <br /> on both sides) do not need this.',
           snippet:'<!-- Inline image (needs vertical-align) -->\nsome text <img src="..." alt="..." style="vertical-align:middle;" /> more text\n\n<!-- Standalone image (no vertical-align needed) -->\n<br /><img src="..." alt="..." /><br />'} },

    { id:'img-standalone-has-valign', category:'images', severity:'error',
      description:'Standalone images must not have style="vertical-align:middle;" — that style is only for images inline with text',
      type:'img-inline-valign-check', subtype:'unnecessary',
      message:'Line {line} has a standalone image (<br /> on both sides) with style="vertical-align:middle;" — remove it.',
      fix:{description:'Remove style="vertical-align:middle;" from images that are on their own line (surrounded by <br /> on both sides). The style is only needed when an image appears inline alongside text content.',
           snippet:'<!-- Standalone image — no vertical-align needed -->\n<br /><img src="..." alt="..." /><br />\n\n<!-- Inline image — vertical-align required -->\nsome text <img src="..." alt="..." style="vertical-align:middle;" /> more text'} },

   { id:'img-ambiguous-valign', category:'images', severity:'warning',
      description:'Image has <br /> on one side only — intent is ambiguous',
      type:'img-inline-valign-check', subtype:'ambiguous',
      message:'Line {line} has an image with <br /> on one side only — determine whether image is inline or standalone.',
      rationale:'A <br /> on one side but not the other suggests the image placement may be unintentional. If the image should be standalone, add a <br /> on the missing side and remove vertical-align:middle;. If it is inline with text, remove the <br /> and keep the style.',
      fix:{description:'Determine how the image is being used. See details for table instructions.',
           htmlDescription:'Determine how the image is being used:<br><br><table style="width:100%; border-collapse:collapse; font-size:11.5px; margin-bottom:8px;"><tr><th style="border:1px solid var(--border); padding:6px 8px; background:var(--surface2); text-align:left;">Image Use</th><th style="border:1px solid var(--border); padding:6px 8px; background:var(--surface2); text-align:left;">Fix</th></tr><tr><td style="border:1px solid var(--border); padding:6px 8px;"><strong>Inline Image</strong><br><span style="color:var(--text-dim); font-size:10px;">(image appears within a sentence)</span></td><td style="border:1px solid var(--border); padding:6px 8px;">&bull; Remove any extra <code>&lt;br /&gt;</code> tags around the image<br>&bull; Ensure image includes: <code>style="vertical-align:middle;"</code></td></tr><tr><td style="border:1px solid var(--border); padding:6px 8px;"><strong>Standalone Image</strong><br><span style="color:var(--text-dim); font-size:10px;">(image appears on its own line)</span></td><td style="border:1px solid var(--border); padding:6px 8px;">&bull; Ensure there are <code>&lt;br /&gt;</code> tags before and after the image<br>&bull; Remove <code>style="vertical-align:middle;" (if present)</code></td></tr></table>',
           snippet:'\n<br /><img src="..." alt="..." /><br />\n\n\nsome text <img src="..." alt="..." style="vertical-align:middle;" /> more text'} },

    { id:'img-absmiddle', category:'images', severity:'error',
      description:'align="absmiddle" on images is deprecated — replace with style="vertical-align:middle;"',
      type:'img-absmiddle-check',
      message:'Line {line} uses align="absmiddle" — replace with style="vertical-align:middle;".',
      fix:{description:'Remove align="absmiddle" and replace with the correct inline style.',
           snippet:'<img src="..." alt="..." style="vertical-align:middle;" />'} },

    { id:'accessible-symbols-degree', category:'accessibility', severity:'warning',
      description:'Raw degree symbol (°) must use HTML entity',
      type:'accessible-symbols-check', subtype:'degree',
      message:'Line {line} contains "{found}" — {fix}.',
      rationale:'Screen readers and some rendering engines do not reliably handle the raw degree symbol (°). Use &deg; or spell out "degrees" to ensure consistent display and accessibility.',
      fix:{description:'Replace the raw ° symbol with &deg; (or spell out "degrees").',
           snippet:'90&deg;  or  90 degrees  (not 90°)'} },

    { id:'accessible-symbols-minus', category:'accessibility', severity:'warning',
      description:'Math minus signs should use HTML entities',
      type:'accessible-symbols-check', subtype:'minus',
      message:'Line {line} contains "{found}" — {fix}.',
      rationale:'Screen readers and some rendering engines do not reliably handle inline math minus signs. Use &minus; for subtraction and negative numbers to ensure consistent display and accessibility.',
      fix:{description:'Replace math minus signs with &minus;.',
           snippet:'&minus;5  (not -5 as negative number)\nx &minus; y (not x - y)'} },

    { id:'en-dash-context', category:'accessibility', severity:'warning',
      description:'En dash detected — could be a minus sign or a special character',
      type:'en-dash-context-check',
      message:'Question {num} contains an en dash (–) that needs context review.',
      fix:{description:'Review the en dash in context and replace with the appropriate HTML entity.',
           snippet:'&minus;  — Minus sign (math/negative numbers)\n&ndash;  — En dash (ranges, e.g. 2–4)'} },

    { id:'special-chars-auto', category:'accessibility', severity:'error',
      description:'Word-paste characters must be replaced with their HTML equivalents',
      type:'special-chars-check', tier:'auto',
      message:'Question {num} contains characters that will cause display or accessibility issues.',
      fix:{description:'Replace each flagged character with its correct HTML equivalent. Use the Apply Fix button to fix all automatically.',
           snippet:'\u201c\u201d \u2018\u2019  \u2192  &ldquo;&rdquo; &lsquo;&rsquo;\n\u2014  \u2192  &mdash;\n\u2013  \u2192  &ndash;\n\u00a9  \u2192  &copy;\n\u00ae \u2122 \u2120  \u2192  <sup>&reg;</sup> <sup>&trade;</sup> <sup>&#8480;</sup>\n\u00d7  \u2192  &times;\n\u00f7  \u2192  &divide;\n\u00a0  \u2192  (remove or use a regular space)'} },
    

    { id:'special-chars-review', category:'accessibility', severity:'warning',
      description:'Unusual characters found — review and replace with HTML entities or plain text',
      type:'special-chars-check', tier:'review',
      message:'Question {num} contains characters that should be reviewed for LMS compatibility.',
      rationale:'These characters may not render correctly in all browsers or be read accurately by screen readers. Review each one and replace with the appropriate HTML entity or plain text equivalent.',
      fix:{description:'Review each character and replace with its HTML entity or a plain text equivalent.',
           snippet:'\u03b1  \u2192  &alpha;  or  "alpha"\n\u00bd  \u2192  &frac12;  or  "1/2"\n\u2192  \u2192  &rarr;  or  "to"\n\u00b2  \u2192  <sup>2</sup>'} },

    { id:'replacement-char', category:'accessibility', severity:'error',
      description:'Unicode replacement character \uFFFD found — original character was lost during encoding',
      type:'replacement-char-check',
      message:'Line {line} contains a Unicode replacement character \uFFFD (U+FFFD) — the original character was corrupted during copy/paste or file encoding.',
      fix:{description:'The \uFFFD character means the source text had an encoding error. You must identify what the original character was from the source document and retype it correctly — it cannot be recovered automatically.',
           snippet:'Look at the original source document to determine what character was intended, then delete \uFFFD and retype the correct character or HTML entity.'} },

    { id:'table-tag-pairs', category:'tables', severity:'error',
      description:'All table tags must have matching opening and closing tags in the correct order',
      type:'table-check', subtype:'tag-pairs',
      message:'Table at line {line}: {found}.',
      fix:{description:'Ensure every table structural tag has a matching opening and closing tag. Check for missing </tr>, </td>, </th>, </thead>, or </tbody> tags.',
           snippet:'<table>\n  <thead><tr><th>...</th></tr></thead>\n  <tbody><tr><td>...</td></tr></tbody>\n</table>'} },

    { id:'table-required-sections', category:'tables', severity:'error',
      description:'Tables must include both a <thead> with <th> headers and a <tbody>',
      type:'table-check', subtype:'required-sections',
      message:'Table at line {line}: {found}.',
      fix:{description:'Every table must have a <thead> section containing <th> header cells, and a <tbody> section containing the data rows.',
           snippet:'<table border="1" cellpadding="5">\n  <thead>\n    <tr><th scope="col">Header</th></tr>\n  </thead>\n  <tbody>\n    <tr><td>Data</td></tr>\n  </tbody>\n</table>'} },

    { id:'table-border-cellpadding', category:'tables', severity:'error',
      description:'Tables must have border="1" and cellpadding set to a number',
      type:'table-check', subtype:'border-cellpadding',
      message:'Table at line {line}: {found}.',
      fix:{description:'The opening <table> tag must include border="1" and cellpadding="N" where N is a number (e.g. 5).',
           snippet:'<table border="1" cellpadding="10">'} },

    { id:'table-th-scope', category:'tables', severity:'warning',
      description:'<th> tags should include a scope attribute (col, row, colgroup, or rowgroup)',
      type:'table-check', subtype:'th-scope',
      message:'Table at line {line}: {found}.',
      rationale:'The scope attribute helps screen readers associate header cells with their data cells. Use scope="col" for column headers (in thead) and scope="row" for row headers (first cell of each tbody row).',
      fix:{description:'Add scope="col" to <th> tags in the header row and scope="row" to <th> tags that act as row labels in the body.',
           snippet:'<!-- Column headers -->\n<th scope="col">Name</th>\n\n<!-- Row header -->\n<th scope="row">Row Label</th>'} },

    { id:'table-structure-malformed', category:'tables', severity:'error',
      description:'Table row and cell structure must not be malformed — column counts must be consistent',
      type:'table-check', subtype:'structure',
      message:'Table at line {line}: {found}.',
      fix:{description:'Each row should have the same effective number of columns (accounting for colspan/rowspan). Check for missing or extra cells.',
           snippet:'<tr><td>Col 1</td><td>Col 2</td></tr>  <!-- 2 cols -->\n<tr><td colspan="2">Merged</td></tr>  <!-- also 2 cols, OK -->'} },

    { id:'table-align-center', category:'tables', severity:'error',
      description:'Tables must not use align="center" — use style="text-align: center;" instead',
      type:'table-check', subtype:'align-center',
      message:'Table at line {line}: {found} — use style="text-align: center;" instead.',
      fix:{description:'Replace align="center" on any table element with the equivalent inline style.',
           snippet:'<!-- Wrong -->\n<td align="center">text</td>\n\n<!-- Correct -->\n<td style="text-align: center;">text</td>'} },

   { id:'font-tag-replace', category:'html-tags', severity:'error',
      description:'Font tags must be replaced with equivalent span style tags',
      type:'font-tag-check',
      message:'Line {line} uses <font face="..."> — replace with <span style="font-family:...">.',
      fix:{description:'Replace <font face="..."> with a span using font-family style.',
           snippet:"\n<font face=\"courier new\">text</font>\n\n\n<span style=\"font-family: 'Courier New', Courier, monospace;\">text</span>"} },

    { id:'underscore-format', category:'question-structure', severity:'error',
      description:'Fill-in-the-blank underscores must be exactly 3 (___) for numbers or 8 (________) for words, with spaces around them',
      type:'underscore-format-check',
      message:'Line {line} has an invalid underscore sequence "{found}".',
      fix:{description:'Adjust underscores to exactly 3 or 8, and ensure there is a space before and after the sequence.',
           snippet:'\nWhat is the ____ shape?\nThe shape is____.\n\n\nWhat is the ________ shape?\nThe shape is ________.'} }
  ]
};

